spring:
  profiles:
    include: infra
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql : true
    open-in-view: false
  data:
    web:
      pageable:
        default-page-size: 300
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
logging.level:
  org.hibernate.SQL: debug