spring:
  profiles:
    include: infra
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql : true
    open-in-view: false
logging.level:
  org.hibernate.SQL: debug